version: "3.1"
services:
  app:
    build: .
    ports:
      - "9000:9000"
      - "8181:8181"
    volumes:
      - ./:/app
    links:
      - db
      - redis
    environment:
      - PORT=9000
      - REDIS_URL=redis://redis:6379
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
