version: "3.1"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8181:8181"
      - "9000:9000"
    volumes:
      - ./app:/app
      - ./:/app
    links:
      - db
      - redis
    environment:
      - PORT=9000
      - REDIS_URL=redis://redis:6379
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=analise
      - DB_HOST=host.docker.internal
      - DB_DIALECT=mysql
      - DB_PORT=3307
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    expose:
      - "3307"
    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  docs:
    image: nginx
    ports:
      - 4040:80
    volumes:
      - ./docs:/usr/share/nginx/html
